
module Institue {

    // Define the structure for an Epreuve
    struct Epreuve {
        string nom;
        double note;
        double coefficient;
    };

    // Define the structure for a Livre
    struct Livre {
        long numero;
        string nom;
        string auteur;
        string collection;
        string date_publication;
    };

    typedef sequence<string> StringList;
    typedef sequence<Livre> LivreList;
    // Define the interface for an Etudiant
    interface Etudiant {
        void AjouterUneEpreuve(in string nom,in double note,in double coefficient);
        StringList ListeDesEpreuves(); // Return a list of strings
        double CalculerLaMoyenne();
        Livre EmprunterUnLivre(in long bookNumber); // Pass a sequence of Livre
        string toStringIDL();
    };

    // Define the interface for a Promotion
    interface Promotion {
        void AjouterUnEtudiant(in long numero,in string nom,in string prenom);
        Etudiant RechercherUnEtudiant(in long numero); // Search for a student by number
        double CalculerMoyenneDeLaPromotion();
    };
};
