package Institue;


/**
* Institue/_PromotionStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Institue.idl
* Wednesday, December 18, 2024 6:39:06 PM WAT
*/


// Define the interface for a Promotion
public class _PromotionStub extends org.omg.CORBA.portable.ObjectImpl implements Institue.Promotion
{

  public void AjouterUnEtudiant (int numero, String nom, String prenom)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("AjouterUnEtudiant", true);
                $out.write_long (numero);
                $out.write_string (nom);
                $out.write_string (prenom);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                AjouterUnEtudiant (numero, nom, prenom        );
            } finally {
                _releaseReply ($in);
            }
  } // AjouterUnEtudiant

  public Institue.Etudiant RechercherUnEtudiant (int numero)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("RechercherUnEtudiant", true);
                $out.write_long (numero);
                $in = _invoke ($out);
                Institue.Etudiant $result = Institue.EtudiantHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return RechercherUnEtudiant (numero        );
            } finally {
                _releaseReply ($in);
            }
  } // RechercherUnEtudiant


  // Search for a student by number
  public double CalculerMoyenneDeLaPromotion ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("CalculerMoyenneDeLaPromotion", true);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return CalculerMoyenneDeLaPromotion (        );
            } finally {
                _releaseReply ($in);
            }
  } // CalculerMoyenneDeLaPromotion

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Institue/Promotion:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _PromotionStub
