package Institue;

/**
* Institue/EpreuveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Institue.idl
* Wednesday, December 18, 2024 6:39:06 PM WAT
*/

public final class EpreuveHolder implements org.omg.CORBA.portable.Streamable
{
  public Institue.Epreuve value = null;

  public EpreuveHolder ()
  {
  }

  public EpreuveHolder (Institue.Epreuve initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Institue.EpreuveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Institue.EpreuveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Institue.EpreuveHelper.type ();
  }

}
