package Institue;


/**
* Institue/Etudiant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Institue.idl
* Wednesday, December 18, 2024 6:39:06 PM WAT
*/


// Define the interface for an Etudiant
public interface Etudiant extends EtudiantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Etudiant
