package Institue;


/**
* Institue/EtudiantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Institue.idl
* Wednesday, December 18, 2024 6:39:06 PM WAT
*/


// Define the interface for an Etudiant
public interface EtudiantOperations 
{
  void AjouterUneEpreuve (String nom, double note, double coefficient);
  String[] ListeDesEpreuves ();

  // Return a list of strings
  double CalculerLaMoyenne ();
  Institue.Livre EmprunterUnLivre (int bookNumber);

  // Pass a sequence of Livre
  String toStringIDL ();
} // interface EtudiantOperations
