package Institue;

/**
* Institue/EtudiantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Institue.idl
* Wednesday, December 18, 2024 6:39:06 PM WAT
*/


// Define the interface for an Etudiant
public final class EtudiantHolder implements org.omg.CORBA.portable.Streamable
{
  public Institue.Etudiant value = null;

  public EtudiantHolder ()
  {
  }

  public EtudiantHolder (Institue.Etudiant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Institue.EtudiantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Institue.EtudiantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Institue.EtudiantHelper.type ();
  }

}
