package Institue;

/**
* Institue/PromotionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Institue.idl
* Wednesday, December 18, 2024 6:39:06 PM WAT
*/


// Define the interface for a Promotion
public final class PromotionHolder implements org.omg.CORBA.portable.Streamable
{
  public Institue.Promotion value = null;

  public PromotionHolder ()
  {
  }

  public PromotionHolder (Institue.Promotion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Institue.PromotionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Institue.PromotionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Institue.PromotionHelper.type ();
  }

}
